Math magician: Fetch data from an API
Munyabelden/calculator pull request #3
Opened 2023-03-30 15:34 UTC by Munyabelden

### This PR is for

- Fetching a quote from the API Ninja and display on screen
- Added a loading and error state

**Thank you for the review** 😊

2023-03-30 16:10 UTC, Lizdev-05 requested changes
Hi @Munyabelden, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
<img src="https://media3.giphy.com/media/h7u3pLvYK3HfQ4yXxW/giphy.gif"/>
## Highlights
*  Descriptive Pull Request message ✔️
*  Good use of GitHub flow ✔️
*  No linter error ✔️
*  Brilliant implementation ✔️

## Required Changes ♻️
_Check the comments under the review._
- The app is currently throwing an error from the import of components which is making it unable to view the project. Kindly work on it. 🥺 
<img width="1395" alt="image" src="https://user-images.githubusercontent.com/73854999/228898173-3b1628f7-836d-4a40-80e1-09020aac7433.png">

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-30 16:10 UTC, Lizdev-05 commented on src/components/displayQoute.js
> +  const [loading, setLoading] = useState(false);
Great job on the implementation 👍 . According to the requirement, there should be an error state, kindly implement it. 🥺

2023-03-30 18:15 UTC, TadesseDev requested changes
### Hi @Munyabelden 

### I'm Tadesse Alemayehu your reviewer for this PR. :hand: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![212094426-b41dd457-c9db-4ab3-bbe9-176dd8dd08b7](https://user-images.githubusercontent.com/69077061/212385281-4797c58a-d358-423a-aa7c-832c22203865.gif)




## Highlights
- [x] Good job making most of the changes requested by the previous code reviewer. 


## Required Changes ♻️
- [ ] Dear @Munyabelden, as mentioned by the previous reviewer, the app is currently throwing an error from the import of components which is making it unable to view the project. Kindly work on it. 🥺
![image](https://user-images.githubusercontent.com/69077061/228927430-0ba0e55a-59b7-45a5-9b2a-93d9a80e12cf.png)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 09:08 UTC, Lizdev-05 approved these changes
Hi @Munyabelden, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media3.giphy.com/media/pCO5tKdP22RC8/giphy.gif"/>
## Highlights

-  Descriptive Pull Request message ✔️
-  Good use of GitHub flow ✔️
-  No linter error ✔️
-  Brilliant implementation ✔️
- ## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-31 09:11 UTC, merged