Components tests
Munyabelden/calculator pull request #5
Opened 2023-04-05 16:15 UTC by Munyabelden

### This PR is for

- Added test for all my commponent files

**thank you for reviewing my PR😉**

2023-04-05 18:03 UTC, Zuhaib042 requested changes
Hi @Munyabelden , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![](https://media.giphy.com/media/3o7qDQAFlF8mZjv6fK/giphy.gif)
## Highlights
✅ Professional Readme
✅ No linters errors
## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- x
- y
- z

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-05 18:03 UTC, Zuhaib042 commented on src/components/__tests__/home.test.js
> +​
- [ ] This test is failing. kindly consider adding a `describe` block here. that could be the reason for the failed test.

2023-04-05 18:03 UTC, Zuhaib042 commented on src/components/__tests__/calculator.test.js
> +  const result = screen.getByTestId("result");
- [ ] This line is the reason for another failing test. kindly consider fixing it before submitting for review as we should pass all the tests as per project requirements.

2023-04-05 18:03 UTC, Zuhaib042 commented on src/components/__tests__/calculator.test.js
> +  const result = screen.getByTestId("result");
- [ ] This line is the reason for another failing test. kindly consider fixing it before submitting for review as we should pass all the tests as per project requirements.

2023-04-05 18:03 UTC, Zuhaib042 commented on src/components/__tests__/calculator.test.js
> +  const result = screen.getByTestId("result");
- [ ] This line is the reason for another failing test. kindly consider fixing it before submitting for review as we should pass all the tests as per project requirements.

2023-04-05 18:03 UTC, Zuhaib042 commented on src/components/__tests__/calculator.test.js
> +  const result = screen.getByTestId("result");
- [ ] This line is the reason for another failing test. kindly consider fixing it before submitting for review as we should pass all the tests as per project requirements.

2023-04-06 06:09 UTC, didierganthier approved these changes
Hi @Munyabelden  and @sumon766 ,

Congratulations! 🎉 Your project is complete and ready to be merged! 🚀

<img src="https://media.giphy.com/media/l9CSJHK88kMTe/giphy.gif" />

## Highlights
- Descriptive PR ✔️ 
- Linters passing ✔️ 
- Tests passing✔️ 

## Optional Suggestions 💡
- [ ] Well done overall 💯  but also consider making usage of Jest snapshots for testing all the components. 🤓 

Cheers and Happy coding!👏👏👏

If you have any questions or need clarification on anything, feel free to leave a comment in the pull request thread and don't forget to tag me so I'll receive the notification.

------
As per the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561), you have a limited number of reviews per project. If you feel that the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). 

Once again, congratulations on completing this project! 🎉

2023-04-06 08:08 UTC, merged